name: Build

on:
  push:
    branches: [ v0.7 ]
  pull_request:
    branches: [ v0.7 ]

jobs:
  Ubuntu:
    name: Ubuntu latest build
    runs-on: ubuntu-latest
    permissions: write-all
  
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Update repository
      run: sudo apt update -y

    - name: Install the basic dev packages

      run: sudo apt install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++ 

    - name: Install build dependencies
      run: sudo mk-build-deps -i -t "apt-get --yes" -r

    - name: Build Package
      run: sudo dpkg-buildpackage -b -uc -us -nc -tc -j$(nproc)

    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d-%s')"

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "0.7"
        prerelease: false
        title: "Version 0.7 - ${{ steps.date.outputs.today }}"
        files: |
          ../**/*.deb
          ../**/*.ddeb
          ../**/*.buildinfo
          ../**/*.changes
